config:
  name: arch-brokerage-intercessor-configmap
  port: 8000
  ddl: validate
secret:
  name: arch-brokerage-intercessor-secret
deployment:
  app:
    image: gurok/arch_brokerage_intercessor
    port: 8000
    replicas: 2
  db:
    image: postgres:latest
    port: 5432
    replicas: 1
service:
  app:
    name: arch-brokerage-intercessor-service
    type: ClusterIP
    protocol: TCP
    port: 9000
  db:
    name: postgresql-brokerage-intercessor-service
    host: "postgresql-brokerage-intercessor-service"
    type: ClusterIP
    port: 5432
    sport: "5432"
    dbname: arch_brokerage_intercessor_db
    dbschema: public
ingress:
  name: otus-project-ingress
  host: arch.homework